import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import "./landing.css";
import Header from "../../components/header/header";
import { ArrowRight, BookOpen, Brain, Target, Users } from "lucide-react";

const LandingPage = () => {
  const navigate = useNavigate();
  const isLoggedIn = localStorage.getItem('userLoggedIn') === 'true';

  // Redirect logged-in users to their profile
  useEffect(() => {
    if (isLoggedIn) {
      navigate('/profile');
    }
  }, [isLoggedIn, navigate]);

  const features = [
    {
      icon: <Brain size={40} />,
      title: "AI-Powered Learning",
      description: "Get personalized learning roadmaps generated by advanced AI technology"
    },
    {
      icon: <Target size={40} />,
      title: "Structured Progress",
      description: "Track your learning journey with detailed progress visualization"
    },
    {
      icon: <BookOpen size={40} />,
      title: "Interactive Quizzes",
      description: "Test your knowledge with AI-generated quizzes and assessments"
    },
    {
      icon: <Users size={40} />,
      title: "Personalized Experience",
      description: "Tailored content based on your skill level and available time"
    }
  ];

  return (
    <div className="wrapper">
      <Header />
      <div className="flexbox main landingMain">
        
        {/* Hero Section */}
        <div className="heroSection flexbox">
          <div className="heroContent">
            <h1 className="heroTitle">Learn Anything Easily</h1>
            <h2 className="heroSubtitle">With Personalized AI-Powered Learning Paths</h2>
            <p className="heroDescription">
              Create customized learning roadmaps, track your progress, and master any skill 
              with our intelligent learning platform powered by advanced AI technology.
            </p>
            
            <div className="heroButtons flexbox">
              <button 
                className="SubmitButton primaryButton"
                onClick={() => navigate('/register')}
              >
                Get Started <ArrowRight size={25} />
              </button>
              <button 
                className="secondaryButton"
                onClick={() => navigate('/login')}
              >
                Sign In
              </button>
            </div>
          </div>
        </div>

        {/* Features Section */}
        <div className="featuresSection">
          <h2 className="sectionTitle">Why Choose Our Platform?</h2>
          <div className="featuresGrid flexbox">
            {features.map((feature, index) => (
              <div key={index} className="featureCard">
                <div className="featureIcon" style={{ "--clr": index % 2 === 0 ? "#D14EC4" : "#AFD14E" }}>
                  {feature.icon}
                </div>
                <h3 className="featureTitle">{feature.title}</h3>
                <p className="featureDescription">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Demo Section */}
        <div className="demoSection">
          <h2 className="sectionTitle">See It In Action</h2>
          <p className="demoDescription">
            Experience the power of AI-driven personalized learning
          </p>
          <button 
            className="SubmitButton demoButton"
            onClick={() => navigate('/topic')}
          >
            Try Demo (No Registration Required)
          </button>
        </div>
      </div>
    </div>
  );
};

export default LandingPage;
